var regionListHelper = [{ id: 1826, label: 'Россия', url: '../../../www.company.mts.ru/default.htm', letter: '', iscountry: 1, parent: 0, sitesection: '', isLink: false },
{ id: 3163, label: 'Туркменистан', url: '../../../www.mts.tm/tm/default.htm', letter: '', iscountry: 1, parent: 0, sitesection: '', isLink: false },
{ id: 3161, label: 'Украина', url: '../../../www.mts.com.ua/default.htm', letter: '', iscountry: 1, parent: 0, sitesection: '', isLink: false },
{ id: 3160, label: 'Республика Беларусь', url: '../../../www.mts.by/default.htm', letter: '', iscountry: 1, parent: 0, sitesection: '', isLink: false },
{ id: 3162, label: 'Узбекистан', url: '../../../www.mts.uz/default.htm', letter: '', iscountry: 1, parent: 0, sitesection: '', isLink: false },
{ id: 3165, label: 'Армения', url: '../../../www.mts.am/default.htm', letter: '', iscountry: 1, parent: 0, sitesection: '', isLink: false },
{ id: 1750, label: 'Алания (Республика Северная Осетия - Алания), Владикавказ', url: '../../../pdealer.mts.ru/', letter: 'А', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1750, label: 'Алания (Республика Северная Осетия - Алания), Владикавказ', url: '../../../www.alania.mts.ru/default.htm', letter: 'А', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1750, label: 'Алания (Республика Северная Осетия - Алания), Владикавказ', url: '../../../www.vip.alania.mts.ru/default.htm', letter: 'А', iscountry: 0, parent: 0, sitesection: 'vip', isLink: false },
{ id: 1750, label: 'Алания (Республика Северная Осетия - Алания), Владикавказ', url: '../../../www.corp.alania.mts.ru/default.htm', letter: 'А', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1750, label: 'Алания (Республика Северная Осетия - Алания), Владикавказ', url: '../../../www.company.alania.mts.ru/default.htm', letter: 'А', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1750, label: 'Алания (Республика Северная Осетия - Алания), Владикавказ', url: '../../../sms.alania.mts.ru/default.htm', letter: 'А', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1750, label: 'Алания (Республика Северная Осетия - Алания), Владикавказ', url: '../../../www.dealers.alania.mts.ru/default.htm', letter: 'А', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1751, label: 'Алтай (Республика Алтай) — Горно-Алтайск', url: '../../../www.altai.mts.ru/default.htm', letter: 'А', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1751, label: 'Алтай (Республика Алтай) — Горно-Алтайск', url: '../../../www.corp.altai.mts.ru/default.htm', letter: 'А', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1751, label: 'Алтай (Республика Алтай) — Горно-Алтайск', url: '../../../www.company.altai.mts.ru/default.htm', letter: 'А', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1751, label: 'Алтай (Республика Алтай) — Горно-Алтайск', url: '../../../sms.altai.mts.ru/default.htm', letter: 'А', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1751, label: 'Алтай (Республика Алтай) — Горно-Алтайск', url: '../../../pdealer.mts.ru/default.htm', letter: 'А', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1751, label: 'Алтай (Республика Алтай) — Горно-Алтайск', url: '../../../www.dealers.altai.mts.ru/default.htm', letter: 'А', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1752, label: 'Алтайский край — Барнаул', url: '../../../www.barnaul.mts.ru/default.htm', letter: 'А', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1752, label: 'Алтайский край — Барнаул', url: '../../../www.corp.barnaul.mts.ru/default.htm', letter: 'А', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1752, label: 'Алтайский край — Барнаул', url: '../../../www.company.barnaul.mts.ru/default.htm', letter: 'А', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1752, label: 'Алтайский край — Барнаул', url: '../../../sms.barnaul.mts.ru/default.htm', letter: 'А', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1752, label: 'Алтайский край — Барнаул', url: '../../../pdealer.mts.ru/default.htm', letter: 'А', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1752, label: 'Алтайский край — Барнаул', url: '../../../www.dealers.barnaul.mts.ru/default.htm', letter: 'А', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1753, label: 'Амурская область — Благовещенск', url: '../../../www.amur.mts.ru/default.htm', letter: 'А', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1753, label: 'Амурская область — Благовещенск', url: '../../../www.corp.amur.mts.ru/default.htm', letter: 'А', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1753, label: 'Амурская область — Благовещенск', url: '../../../www.company.amur.mts.ru/default.htm', letter: 'А', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1753, label: 'Амурская область — Благовещенск', url: '../../../sms.amur.mts.ru/default.htm', letter: 'А', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1753, label: 'Амурская область — Благовещенск', url: '../../../pdealer.mts.ru/default.htm', letter: 'А', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1753, label: 'Амурская область — Благовещенск', url: '../../../www.dealers.amur.mts.ru/default.htm', letter: 'А', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1754, label: 'Архангельская область', url: '../../../pdealer.mts.ru/default.htm', letter: 'А', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1754, label: 'Архангельская область', url: '../../../www.arkhangelsk.mts.ru/default.htm', letter: 'А', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1754, label: 'Архангельская область', url: '../../../www.corp.arkhangelsk.mts.ru/default.htm', letter: 'А', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1754, label: 'Архангельская область', url: '../../../www.company.arkhangelsk.mts.ru/default.htm', letter: 'А', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1754, label: 'Архангельская область', url: '../../../sms.arkhangelsk.mts.ru/default.htm', letter: 'А', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1754, label: 'Архангельская область', url: '../../../www.dealers.arkhangelsk.mts.ru/default.htm', letter: 'А', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1755, label: 'Астраханская область', url: '../../../pdealer.mts.ru/', letter: 'А', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1755, label: 'Астраханская область', url: '../../../www.astrakhan.mts.ru/default.htm', letter: 'А', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1755, label: 'Астраханская область', url: '../../../www.vip.astrakhan.mts.ru/default.htm', letter: 'А', iscountry: 0, parent: 0, sitesection: 'vip', isLink: false },
{ id: 1755, label: 'Астраханская область', url: '../../../www.corp.astrakhan.mts.ru/default.htm', letter: 'А', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1755, label: 'Астраханская область', url: '../../../www.company.astrakhan.mts.ru/default.htm', letter: 'А', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1755, label: 'Астраханская область', url: '../../../www.sms.astrakhan.mts.ru/default.htm', letter: 'А', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1755, label: 'Астраханская область', url: '../../../www.dealers.astrakhan.mts.ru/default.htm', letter: 'А', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1945119, label: 'Балашиха', url: '../../../www.balashiha.mts.ru/default.htm', letter: 'Б', iscountry: 0, parent: 1826, sitesection: 'ab', isLink: false },
{ id: 1945119, label: 'Балашиха', url: '../../../www.corp.balashiha.mts.ru/default.htm', letter: 'Б', iscountry: 0, parent: 1826, sitesection: 'corp', isLink: false },
{ id: 1945119, label: 'Балашиха', url: '../../../www.company.balashiha.mts.ru/default.htm', letter: 'Б', iscountry: 0, parent: 1826, sitesection: 'comp', isLink: false },
{ id: 1945119, label: 'Балашиха', url: '../../../www.dealers.balashiha.mts.ru/default.htm', letter: 'Б', iscountry: 0, parent: 1826, sitesection: 'partn', isLink: false },
{ id: 1756, label: 'Башкортостан (Республика Башкортостан) — Уфа', url: '../../../pdealer.mts.ru/default.htm', letter: 'Б', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1756, label: 'Башкортостан (Республика Башкортостан) — Уфа', url: '../../../www.bashkortostan.mts.ru/default.htm', letter: 'Б', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1756, label: 'Башкортостан (Республика Башкортостан) — Уфа', url: '../../../www.corp.bashkortostan.mts.ru/default.htm', letter: 'Б', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1756, label: 'Башкортостан (Республика Башкортостан) — Уфа', url: '../../../www.company.bashkortostan.mts.ru/default.htm', letter: 'Б', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1756, label: 'Башкортостан (Республика Башкортостан) — Уфа', url: '../../../sms.bashkortostan.mts.ru/default.htm', letter: 'Б', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1756, label: 'Башкортостан (Республика Башкортостан) — Уфа', url: '../../../www.dealers.bashkortostan.mts.ru/default.htm', letter: 'Б', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1757, label: 'Белгородская область', url: '../../../pdealer.mts.ru/default.htm', letter: 'Б', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1757, label: 'Белгородская область', url: '../../../www.belgorod.mts.ru/default.htm', letter: 'Б', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1757, label: 'Белгородская область', url: '../../../www.corp.belgorod.mts.ru/default.htm', letter: 'Б', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1757, label: 'Белгородская область', url: '../../../www.company.belgorod.mts.ru/default.htm', letter: 'Б', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1757, label: 'Белгородская область', url: '../../../sms.belgorod.mts.ru/default.htm', letter: 'Б', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1757, label: 'Белгородская область', url: '../../../www.dealers.belgorod.mts.ru/default.htm', letter: 'Б', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1970865, label: 'Бийск', url: '../../../www.biysk.mts.ru/default.htm', letter: 'Б', iscountry: 0, parent: 1752, sitesection: 'ab', isLink: false },
{ id: 1970865, label: 'Бийск', url: '../../../www.corp.biysk.mts.ru/default.htm', letter: 'Б', iscountry: 0, parent: 1752, sitesection: 'corp', isLink: false },
{ id: 1970865, label: 'Бийск', url: '../../../www.company.biysk.mts.ru/default.htm', letter: 'Б', iscountry: 0, parent: 1752, sitesection: 'comp', isLink: false },
{ id: 1970865, label: 'Бийск', url: '../../../www.dealers.biysk.mts.ru/default.htm', letter: 'Б', iscountry: 0, parent: 1752, sitesection: 'partn', isLink: false },
{ id: 1758, label: 'Брянская область', url: '../../../pdealer.mts.ru/default.htm', letter: 'Б', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1758, label: 'Брянская область', url: '../../../www.bryansk.mts.ru/default.htm', letter: 'Б', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1758, label: 'Брянская область', url: '../../../www.corp.bryansk.mts.ru/default.htm', letter: 'Б', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1758, label: 'Брянская область', url: '../../../www.company.bryansk.mts.ru/default.htm', letter: 'Б', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1758, label: 'Брянская область', url: '../../../sms.bryansk.mts.ru/default.htm', letter: 'Б', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1758, label: 'Брянская область', url: '../../../www.dealers.bryansk.mts.ru/default.htm', letter: 'Б', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1759, label: 'Бурятия (Республика Бурятия) — Улан-Удэ', url: '../../../www.buryatia.mts.ru/default.htm', letter: 'Б', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1759, label: 'Бурятия (Республика Бурятия) — Улан-Удэ', url: '../../../www.corp.buryatia.mts.ru/default.htm', letter: 'Б', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1759, label: 'Бурятия (Республика Бурятия) — Улан-Удэ', url: '../../../www.company.buryatia.mts.ru/default.htm', letter: 'Б', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1759, label: 'Бурятия (Республика Бурятия) — Улан-Удэ', url: '../../../sms.buryatia.mts.ru/default.htm', letter: 'Б', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1759, label: 'Бурятия (Республика Бурятия) — Улан-Удэ', url: '../../../pdealer.mts.ru/default.htm', letter: 'Б', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1759, label: 'Бурятия (Республика Бурятия) — Улан-Удэ', url: '../../../www.dealers.buryatia.mts.ru/default.htm', letter: 'Б', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1760, label: 'Владимирская область', url: '../../../pdealer.mts.ru/default.htm', letter: 'В', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1760, label: 'Владимирская область', url: '../../../www.vladimir.mts.ru/default.htm', letter: 'В', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1760, label: 'Владимирская область', url: '../../../www.corp.vladimir.mts.ru/default.htm', letter: 'В', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1760, label: 'Владимирская область', url: '../../../www.company.vladimir.mts.ru/default.htm', letter: 'В', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1760, label: 'Владимирская область', url: '../../../sms.vladimir.mts.ru/default.htm', letter: 'В', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1760, label: 'Владимирская область', url: '../../../www.dealers.vladimir.mts.ru/default.htm', letter: 'В', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1761, label: 'Волгоградская область', url: '../../../pdealer.mts.ru/', letter: 'В', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1761, label: 'Волгоградская область', url: '../../../www.volgograd.mts.ru/default.htm', letter: 'В', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1761, label: 'Волгоградская область', url: '../../../www.vip.volgograd.mts.ru/default.htm', letter: 'В', iscountry: 0, parent: 0, sitesection: 'vip', isLink: false },
{ id: 1761, label: 'Волгоградская область', url: '../../../www.corp.volgograd.mts.ru/default.htm', letter: 'В', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1761, label: 'Волгоградская область', url: '../../../www.company.volgograd.mts.ru/default.htm', letter: 'В', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1761, label: 'Волгоградская область', url: '../../../sms.volgograd.mts.ru/default.htm', letter: 'В', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1761, label: 'Волгоградская область', url: '../../../pdealer.mts.ru/default.htm', letter: 'В', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1761, label: 'Волгоградская область', url: '../../../www.dealers.volgograd.mts.ru/default.htm', letter: 'В', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1762, label: 'Вологодская область', url: '../../../pdealer.mts.ru/default.htm', letter: 'В', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1762, label: 'Вологодская область', url: '../../../www.vologda.mts.ru/default.htm', letter: 'В', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1762, label: 'Вологодская область', url: '../../../www.corp.vologda.mts.ru/default.htm', letter: 'В', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1762, label: 'Вологодская область', url: '../../../www.company.vologda.mts.ru/default.htm', letter: 'В', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1762, label: 'Вологодская область', url: '../../../sms.vologda.mts.ru/default.htm', letter: 'В', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1762, label: 'Вологодская область', url: '../../../www.dealers.vologda.mts.ru/default.htm', letter: 'В', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1763, label: 'Воронежская область', url: '../../../pdealer.mts.ru/default.htm', letter: 'В', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1763, label: 'Воронежская область', url: '../../../www.voronezh.mts.ru/default.htm', letter: 'В', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1763, label: 'Воронежская область', url: '../../../www.corp.voronezh.mts.ru/default.htm', letter: 'В', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1763, label: 'Воронежская область', url: '../../../www.company.voronezh.mts.ru/default.htm', letter: 'В', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1763, label: 'Воронежская область', url: '../../../sms.voronezh.mts.ru/default.htm', letter: 'В', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1763, label: 'Воронежская область', url: '../../../www.dealers.voronezh.mts.ru/default.htm', letter: 'В', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1827, label: 'Дагестан (Республика Дагестан) — Махачкала', url: '../../../pdealer.mts.ru/', letter: 'Д', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1827, label: 'Дагестан (Республика Дагестан) — Махачкала', url: '../../../www.dagestan.mts.ru/default.htm', letter: 'Д', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1827, label: 'Дагестан (Республика Дагестан) — Махачкала', url: '../../../www.vip.dagestan.mts.ru/default.htm', letter: 'Д', iscountry: 0, parent: 0, sitesection: 'vip', isLink: false },
{ id: 1827, label: 'Дагестан (Республика Дагестан) — Махачкала', url: '../../../www.corp.dagestan.mts.ru/default.htm', letter: 'Д', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1827, label: 'Дагестан (Республика Дагестан) — Махачкала', url: '../../../www.company.dagestan.mts.ru/default.htm', letter: 'Д', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1827, label: 'Дагестан (Республика Дагестан) — Махачкала', url: '../../../sms.dagestan.mts.ru/default.htm', letter: 'Д', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1827, label: 'Дагестан (Республика Дагестан) — Махачкала', url: '../../../pdealer.mts.ru/default.htm', letter: 'Д', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1827, label: 'Дагестан (Республика Дагестан) — Махачкала', url: '../../../www.dealers.dagestan.mts.ru/default.htm', letter: 'Д', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1764, label: 'Еврейская АО — Биробиджан', url: '../../../www.eao.mts.ru/default.htm', letter: 'Е', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1764, label: 'Еврейская АО — Биробиджан', url: '../../../www.corp.eao.mts.ru/default.htm', letter: 'Е', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1764, label: 'Еврейская АО — Биробиджан', url: '../../../www.company.eao.mts.ru/default.htm', letter: 'Е', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1764, label: 'Еврейская АО — Биробиджан', url: '../../../sms.eao.mts.ru/default.htm', letter: 'Е', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1764, label: 'Еврейская АО — Биробиджан', url: '../../../pdealer.mts.ru/default.htm', letter: 'Е', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1764, label: 'Еврейская АО — Биробиджан', url: '../../../www.dealers.eao.mts.ru/default.htm', letter: 'Е', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1822, label: 'Забайкальский край — Чита', url: '../../../www.chita.mts.ru/default.htm', letter: 'З', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1822, label: 'Забайкальский край — Чита', url: '../../../www.corp.chita.mts.ru/default.htm', letter: 'З', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1822, label: 'Забайкальский край — Чита', url: '../../../www.company.chita.mts.ru/default.htm', letter: 'З', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1822, label: 'Забайкальский край — Чита', url: '../../../sms.chita.mts.ru/default.htm', letter: 'З', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1822, label: 'Забайкальский край — Чита', url: '../../../pdealer.mts.ru/default.htm', letter: 'З', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1822, label: 'Забайкальский край — Чита', url: '../../../www.dealers.chita.mts.ru/default.htm', letter: 'З', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1765, label: 'Ивановская область', url: '../../../pdealer.mts.ru/default.htm', letter: 'И', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1765, label: 'Ивановская область', url: '../../../www.ivanovo.mts.ru/default.htm', letter: 'И', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1765, label: 'Ивановская область', url: '../../../www.corp.ivanovo.mts.ru/default.htm', letter: 'И', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1765, label: 'Ивановская область', url: '../../../www.company.ivanovo.mts.ru/default.htm', letter: 'И', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1765, label: 'Ивановская область', url: '../../../sms.ivanovo.mts.ru/default.htm', letter: 'И', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1765, label: 'Ивановская область', url: '../../../www.dealers.ivanovo.mts.ru/default.htm', letter: 'И', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1767, label: 'Ингушетия (Республика Ингушетия) — Магас', url: '../../../pdealer.mts.ru/', letter: 'И', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1767, label: 'Ингушетия (Республика Ингушетия) — Магас', url: '../../../www.magas.mts.ru/default.htm', letter: 'И', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1767, label: 'Ингушетия (Республика Ингушетия) — Магас', url: '../../../www.vip.magas.mts.ru/default.htm', letter: 'И', iscountry: 0, parent: 0, sitesection: 'vip', isLink: false },
{ id: 1767, label: 'Ингушетия (Республика Ингушетия) — Магас', url: '../../../www.corp.magas.mts.ru/default.htm', letter: 'И', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1767, label: 'Ингушетия (Республика Ингушетия) — Магас', url: '../../../www.company.magas.mts.ru/default.htm', letter: 'И', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1767, label: 'Ингушетия (Республика Ингушетия) — Магас', url: '../../../sms.magas.mts.ru/default.htm', letter: 'И', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1767, label: 'Ингушетия (Республика Ингушетия) — Магас', url: '../../../pdealer.mts.ru/default.htm', letter: 'И', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1767, label: 'Ингушетия (Республика Ингушетия) — Магас', url: '../../../www.dealers.magas.mts.ru/default.htm', letter: 'И', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1766, label: 'Иркутская область', url: '../../../www.irkutsk.mts.ru/default.htm', letter: 'И', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1766, label: 'Иркутская область', url: '../../../www.corp.irkutsk.mts.ru/default.htm', letter: 'И', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1766, label: 'Иркутская область', url: '../../../www.company.irkutsk.mts.ru/default.htm', letter: 'И', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1766, label: 'Иркутская область', url: '../../../sms.irkutsk.mts.ru/default.htm', letter: 'И', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1766, label: 'Иркутская область', url: '../../../pdealer.mts.ru/default.htm', letter: 'И', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1766, label: 'Иркутская область', url: '../../../www.dealers.irkutsk.mts.ru/default.htm', letter: 'И', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1768, label: 'Кабардино-Балкарская Республика — Нальчик', url: '../../../pdealer.mts.ru/', letter: 'К', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1768, label: 'Кабардино-Балкарская Республика — Нальчик', url: '../../../www.kbr.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1768, label: 'Кабардино-Балкарская Республика — Нальчик', url: '../../../www.vip.kbr.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'vip', isLink: false },
{ id: 1768, label: 'Кабардино-Балкарская Республика — Нальчик', url: '../../../www.corp.kbr.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1768, label: 'Кабардино-Балкарская Республика — Нальчик', url: '../../../www.company.kbr.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1768, label: 'Кабардино-Балкарская Республика — Нальчик', url: '../../../sms.kbr.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1768, label: 'Кабардино-Балкарская Республика — Нальчик', url: '../../../www.dealers.kbr.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1769, label: 'Калининградская область', url: '../../../pdealer.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1769, label: 'Калининградская область', url: '../../../www.kaliningrad.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1769, label: 'Калининградская область', url: '../../../www.corp.kaliningrad.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1769, label: 'Калининградская область', url: '../../../www.company.kaliningrad.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1769, label: 'Калининградская область', url: '../../../sms.kaliningrad.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1769, label: 'Калининградская область', url: '../../../www.dealers.kaliningrad.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1770, label: 'Калмыкия (Республика Калмыкия) — Элиста', url: '../../../pdealer.mts.ru/', letter: 'К', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1770, label: 'Калмыкия (Республика Калмыкия) — Элиста', url: '../../../www.elista.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1770, label: 'Калмыкия (Республика Калмыкия) — Элиста', url: '../../../www.vip.elista.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'vip', isLink: false },
{ id: 1770, label: 'Калмыкия (Республика Калмыкия) — Элиста', url: '../../../www.corp.elista.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1770, label: 'Калмыкия (Республика Калмыкия) — Элиста', url: '../../../www.company.elista.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1770, label: 'Калмыкия (Республика Калмыкия) — Элиста', url: '../../../sms.elista.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1770, label: 'Калмыкия (Республика Калмыкия) — Элиста', url: '../../../pdealer.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1770, label: 'Калмыкия (Республика Калмыкия) — Элиста', url: '../../../www.dealers.elista.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1771, label: 'Калужская область', url: '../../../pdealer.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1771, label: 'Калужская область', url: '../../../www.kaluga.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1771, label: 'Калужская область', url: '../../../www.corp.kaluga.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1771, label: 'Калужская область', url: '../../../www.company.kaluga.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1771, label: 'Калужская область', url: '../../../sms.kaluga.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1771, label: 'Калужская область', url: '../../../www.dealers.kaluga.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1772, label: 'Камчатский край — Петропавловск-Камчатский', url: '../../../www.kamchatka.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1772, label: 'Камчатский край — Петропавловск-Камчатский', url: '../../../www.corp.kamchatka.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1772, label: 'Камчатский край — Петропавловск-Камчатский', url: '../../../www.company.kamchatka.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1772, label: 'Камчатский край — Петропавловск-Камчатский', url: '../../../sms.kamchatka.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1772, label: 'Камчатский край — Петропавловск-Камчатский', url: '../../../pdealer.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1772, label: 'Камчатский край — Петропавловск-Камчатский', url: '../../../www.dealers.kamchatka.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1773, label: 'Карачаево-Черкесская Республика — Черкесск', url: '../../../pdealer.mts.ru/', letter: 'К', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1773, label: 'Карачаево-Черкесская Республика — Черкесск', url: '../../../www.kchr.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1773, label: 'Карачаево-Черкесская Республика — Черкесск', url: '../../../www.vip.kchr.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'vip', isLink: false },
{ id: 1773, label: 'Карачаево-Черкесская Республика — Черкесск', url: '../../../www.corp.kchr.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1773, label: 'Карачаево-Черкесская Республика — Черкесск', url: '../../../www.company.kchr.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1773, label: 'Карачаево-Черкесская Республика — Черкесск', url: '../../../sms.kchr.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1773, label: 'Карачаево-Черкесская Республика — Черкесск', url: '../../../pdealer.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1773, label: 'Карачаево-Черкесская Республика — Черкесск', url: '../../../www.dealers.kchr.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1774, label: 'Карелия (Республика Карелия) — Петрозаводск', url: '../../../pdealer.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1774, label: 'Карелия (Республика Карелия) — Петрозаводск', url: '../../../www.karelia.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1774, label: 'Карелия (Республика Карелия) — Петрозаводск', url: '../../../www.corp.karelia.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1774, label: 'Карелия (Республика Карелия) — Петрозаводск', url: '../../../www.company.karelia.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1774, label: 'Карелия (Республика Карелия) — Петрозаводск', url: '../../../sms.karelia.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1774, label: 'Карелия (Республика Карелия) — Петрозаводск', url: '../../../www.dealers.karelia.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1775, label: 'Кемеровская область', url: '../../../www.kemerovo.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1775, label: 'Кемеровская область', url: '../../../www.corp.kemerovo.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1775, label: 'Кемеровская область', url: '../../../www.company.kemerovo.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1775, label: 'Кемеровская область', url: '../../../sms.kemerovo.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1775, label: 'Кемеровская область', url: '../../../pdealer.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1775, label: 'Кемеровская область', url: '../../../www.dealers.kemerovo.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1776, label: 'Кировская область', url: '../../../pdealer.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1776, label: 'Кировская область', url: '../../../www.kirov.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1776, label: 'Кировская область', url: '../../../www.corp.kirov.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1776, label: 'Кировская область', url: '../../../www.company.kirov.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1776, label: 'Кировская область', url: '../../../sms.kirov.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1776, label: 'Кировская область', url: '../../../sms.kirov.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1776, label: 'Кировская область', url: '../../../www.dealers.kirov.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1763999, label: 'Кисловодск', url: '../../../www.kislovodsk.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 1806, sitesection: 'ab', isLink: false },
{ id: 1763999, label: 'Кисловодск', url: '../../../www.corp.kislovodsk.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 1806, sitesection: 'corp', isLink: false },
{ id: 1763999, label: 'Кисловодск', url: '../../../www.company.kislovodsk.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 1806, sitesection: 'comp', isLink: false },
{ id: 1763999, label: 'Кисловодск', url: '../../../www.dealers.kislovodsk.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 1806, sitesection: 'partn', isLink: false },
{ id: 1777, label: 'Коми (Республика Коми) — Сыктывкар', url: '../../../pdealer.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1777, label: 'Коми (Республика Коми) — Сыктывкар', url: '../../../www.komi.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1777, label: 'Коми (Республика Коми) — Сыктывкар', url: '../../../www.corp.komi.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1777, label: 'Коми (Республика Коми) — Сыктывкар', url: '../../../www.company.komi.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1777, label: 'Коми (Республика Коми) — Сыктывкар', url: '../../../sms.komi.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1777, label: 'Коми (Республика Коми) — Сыктывкар', url: '../../../www.dealers.komi.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1731655, label: 'Комсомольск-на-Амуре', url: '../../../www.komsomolsk.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 1818, sitesection: 'ab', isLink: false },
{ id: 1731655, label: 'Комсомольск-на-Амуре', url: '../../../www.corp.komsomolsk.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 1818, sitesection: 'corp', isLink: false },
{ id: 1731655, label: 'Комсомольск-на-Амуре', url: '../../../www.company.komsomolsk.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 1818, sitesection: 'comp', isLink: false },
{ id: 1731655, label: 'Комсомольск-на-Амуре', url: '../../../www.dealers.komsomolsk.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 1818, sitesection: 'partn', isLink: false },
{ id: 1778, label: 'Костромская область', url: '../../../pdealer.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1778, label: 'Костромская область', url: '../../../www.kostroma.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1778, label: 'Костромская область', url: '../../../www.corp.kostroma.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1778, label: 'Костромская область', url: '../../../www.company.kostroma.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1778, label: 'Костромская область', url: '../../../sms.kostroma.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1778, label: 'Костромская область', url: '../../../www.dealers.kostroma.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1779, label: 'Краснодарский край', url: '../../../pdealer.mts.ru/', letter: 'К', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1779, label: 'Краснодарский край', url: '../../../www.kuban.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1779, label: 'Краснодарский край', url: '../../../www.vip.kuban.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'vip', isLink: false },
{ id: 1779, label: 'Краснодарский край', url: '../../../www.corp.kuban.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1779, label: 'Краснодарский край', url: '../../../www.company.kuban.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1779, label: 'Краснодарский край', url: '../../../sms.kuban.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1779, label: 'Краснодарский край', url: '../../../pdealer.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1779, label: 'Краснодарский край', url: '../../../www.dealers.kuban.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1780, label: 'Красноярский край — Красноярск', url: '../../../www.kras.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1780, label: 'Красноярский край — Красноярск', url: '../../../www.corp.kras.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1780, label: 'Красноярский край — Красноярск', url: '../../../www.company.kras.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1780, label: 'Красноярский край — Красноярск', url: '../../../sms.kras.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1780, label: 'Красноярский край — Красноярск', url: '../../../pdealer.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1780, label: 'Красноярский край — Красноярск', url: '../../../www.dealers.kras.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1809, label: 'Красноярский край — Норильск', url: '../../../www.norilsk.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1809, label: 'Красноярский край — Норильск', url: '../../../www.corp.norilsk.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1809, label: 'Красноярский край — Норильск', url: '../../../www.company.norilsk.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1809, label: 'Красноярский край — Норильск', url: '../../../sms.norilsk.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1809, label: 'Красноярский край — Норильск', url: '../../../pdealer.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1809, label: 'Красноярский край — Норильск', url: '../../../www.dealers.norilsk.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1781, label: 'Курганская область', url: '../../../pdealer.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1781, label: 'Курганская область', url: '../../../www.kurgan.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1781, label: 'Курганская область', url: '../../../www.corp.kurgan.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1781, label: 'Курганская область', url: '../../../www.company.kurgan.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1781, label: 'Курганская область', url: '../../../sms.kurgan.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1781, label: 'Курганская область', url: '../../../www.dealers.kurgan.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1782, label: 'Курская область', url: '../../../pdealer.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1782, label: 'Курская область', url: '../../../www.kursk.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1782, label: 'Курская область', url: '../../../www.corp.kursk.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1782, label: 'Курская область', url: '../../../www.company.kursk.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1782, label: 'Курская область', url: '../../../sms.kursk.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1782, label: 'Курская область', url: '../../../www.dealers.kursk.mts.ru/default.htm', letter: 'К', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1783, label: 'Липецкая область', url: '../../../pdealer.mts.ru/default.htm', letter: 'Л', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1783, label: 'Липецкая область', url: '../../../www.lipetsk.mts.ru/default.htm', letter: 'Л', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1783, label: 'Липецкая область', url: '../../../www.corp.lipetsk.mts.ru/default.htm', letter: 'Л', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1783, label: 'Липецкая область', url: '../../../www.company.lipetsk.mts.ru/default.htm', letter: 'Л', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1783, label: 'Липецкая область', url: '../../../sms.lipetsk.mts.ru/default.htm', letter: 'Л', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1783, label: 'Липецкая область', url: '../../../www.dealers.lipetsk.mts.ru/default.htm', letter: 'Л', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1784, label: 'Магаданская область', url: '../../../www.magadan.mts.ru/default.htm', letter: 'М', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1784, label: 'Магаданская область', url: '../../../www.corp.magadan.mts.ru/default.htm', letter: 'М', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1784, label: 'Магаданская область', url: '../../../www.company.magadan.mts.ru/default.htm', letter: 'М', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1784, label: 'Магаданская область', url: '../../../sms.magadan.mts.ru/default.htm', letter: 'М', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1784, label: 'Магаданская область', url: '../../../pdealer.mts.ru/default.htm', letter: 'М', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1784, label: 'Магаданская область', url: '../../../www.dealers.magadan.mts.ru/default.htm', letter: 'М', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1967809, label: 'Магнитогорск', url: '../../../www.magnitogorsk.mts.ru/default.htm', letter: 'М', iscountry: 0, parent: 1821, sitesection: 'ab', isLink: false },
{ id: 1967809, label: 'Магнитогорск', url: '../../../www.corp.magnitogorsk.mts.ru/default.htm', letter: 'М', iscountry: 0, parent: 1821, sitesection: 'corp', isLink: false },
{ id: 1967809, label: 'Магнитогорск', url: '../../../www.company.magnitogorsk.mts.ru/default.htm', letter: 'М', iscountry: 0, parent: 1821, sitesection: 'comp', isLink: false },
{ id: 1967809, label: 'Магнитогорск', url: '../../../www.dealers.magnitogorsk.mts.ru/default.htm', letter: 'М', iscountry: 0, parent: 1821, sitesection: 'partn', isLink: false },
{ id: 1785, label: 'Марий Эл (Республика Марий Эл) — Йошкар-Ола', url: '../../../pdealer.mts.ru/default.htm', letter: 'М', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1785, label: 'Марий Эл (Республика Марий Эл) — Йошкар-Ола', url: '../../../www.mari-el.mts.ru/default.htm', letter: 'М', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1785, label: 'Марий Эл (Республика Марий Эл) — Йошкар-Ола', url: '../../../www.corp.mari-el.mts.ru/default.htm', letter: 'М', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1785, label: 'Марий Эл (Республика Марий Эл) — Йошкар-Ола', url: '../../../www.company.mari-el.mts.ru/default.htm', letter: 'М', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1785, label: 'Марий Эл (Республика Марий Эл) — Йошкар-Ола', url: '../../../sms.mari-el.mts.ru/default.htm', letter: 'М', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1785, label: 'Марий Эл (Республика Марий Эл) — Йошкар-Ола', url: '../../../sms.mari-el.mts.ru/default.htm', letter: 'М', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1785, label: 'Марий Эл (Республика Марий Эл) — Йошкар-Ола', url: '../../../www.dealers.mari-el.mts.ru/default.htm', letter: 'М', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1967811, label: 'Миасс', url: '../../../www.miass.mts.ru/default.htm', letter: 'М', iscountry: 0, parent: 1821, sitesection: 'ab', isLink: false },
{ id: 1967811, label: 'Миасс', url: '../../../www.corp.miass.mts.ru/default.htm', letter: 'М', iscountry: 0, parent: 1821, sitesection: 'corp', isLink: false },
{ id: 1967811, label: 'Миасс', url: '../../../www.company.miass.mts.ru/default.htm', letter: 'М', iscountry: 0, parent: 1821, sitesection: 'comp', isLink: false },
{ id: 1967811, label: 'Миасс', url: '../../../www.dealers.miass.mts.ru/default.htm', letter: 'М', iscountry: 0, parent: 1821, sitesection: 'partn', isLink: false },
{ id: 1786, label: 'Мордовия (Республика Мордовия) — Саранск', url: '../../../pdealer.mts.ru/default.htm', letter: 'М', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1786, label: 'Мордовия (Республика Мордовия) — Саранск', url: '../../../www.mordovia.mts.ru/default.htm', letter: 'М', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1786, label: 'Мордовия (Республика Мордовия) — Саранск', url: '../../../www.corp.mordovia.mts.ru/default.htm', letter: 'М', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1786, label: 'Мордовия (Республика Мордовия) — Саранск', url: '../../../www.company.mordovia.mts.ru/default.htm', letter: 'М', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1786, label: 'Мордовия (Республика Мордовия) — Саранск', url: '../../../sms.mordovia.mts.ru/default.htm', letter: 'М', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1786, label: 'Мордовия (Республика Мордовия) — Саранск', url: '../../../sms.mordovia.mts.ru/default.htm', letter: 'М', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1786, label: 'Мордовия (Республика Мордовия) — Саранск', url: '../../../www.dealers.mordovia.mts.ru/default.htm', letter: 'М', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1826, label: 'Москва и Подмосковье', url: '../../../www.mts.ru/default.htm', letter: 'М', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1826, label: 'Москва и Подмосковье', url: '../../default.htm', letter: 'М', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1826, label: 'Москва и Подмосковье', url: '../../../www.company.mts.ru/default.htm', letter: 'М', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1826, label: 'Москва и Подмосковье', url: '../../../www.developer.mts.ru/default.htm', letter: 'М', iscountry: 0, parent: 0, sitesection: 'dev360', isLink: false },
{ id: 1826, label: 'Москва и Подмосковье', url: '../../../dengi.mts.ru/default.htm', letter: 'М', iscountry: 0, parent: 0, sitesection: 'mtsmoney', isLink: false },
{ id: 1826, label: 'Москва и Подмосковье', url: '../../../www.dealers.mts.ru/default.htm', letter: 'М', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1826, label: 'Москва и Подмосковье', url: '../../../safety.mts.ru/default.htm', letter: 'М', iscountry: 0, parent: 0, sitesection: 'safety', isLink: false },
{ id: 1826, label: 'Москва и Подмосковье', url: '../../../test.mts.ru/default.htm', letter: 'М', iscountry: 0, parent: 0, sitesection: 'testinetsettingsroot', isLink: false },
{ id: 1787, label: 'Мурманская область', url: '../../../pdealer.mts.ru/default.htm', letter: 'М', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1787, label: 'Мурманская область', url: '../../../www.murmansk.mts.ru/default.htm', letter: 'М', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1787, label: 'Мурманская область', url: '../../../www.corp.murmansk.mts.ru/default.htm', letter: 'М', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1787, label: 'Мурманская область', url: '../../../www.company.murmansk.mts.ru/default.htm', letter: 'М', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1787, label: 'Мурманская область', url: '../../../sms.murmansk.mts.ru/default.htm', letter: 'М', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1787, label: 'Мурманская область', url: '../../../www.dealers.murmansk.mts.ru/default.htm', letter: 'М', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1789, label: 'Нижегородская область — Нижний Новгород', url: '../../../pdealer.mts.ru/default.htm', letter: 'Н', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1789, label: 'Нижегородская область — Нижний Новгород', url: '../../../www.nnov.mts.ru/default.htm', letter: 'Н', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1789, label: 'Нижегородская область — Нижний Новгород', url: '../../../www.corp.nnov.mts.ru/default.htm', letter: 'Н', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1789, label: 'Нижегородская область — Нижний Новгород', url: '../../../www.company.nnov.mts.ru/default.htm', letter: 'Н', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1789, label: 'Нижегородская область — Нижний Новгород', url: '../../../sms.nnov.mts.ru/default.htm', letter: 'Н', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1789, label: 'Нижегородская область — Нижний Новгород', url: '../../../sms.nnov.mts.ru/default.htm', letter: 'Н', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1789, label: 'Нижегородская область — Нижний Новгород', url: '../../../www.dealers.nnov.mts.ru/default.htm', letter: 'Н', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1790, label: 'Новгородская область — Великий Новгород', url: '../../../pdealer.mts.ru/default.htm', letter: 'Н', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1790, label: 'Новгородская область — Великий Новгород', url: '../../../www.nov.mts.ru/default.htm', letter: 'Н', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1790, label: 'Новгородская область — Великий Новгород', url: '../../../www.corp.nov.mts.ru/default.htm', letter: 'Н', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1790, label: 'Новгородская область — Великий Новгород', url: '../../../www.company.nov.mts.ru/default.htm', letter: 'Н', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1790, label: 'Новгородская область — Великий Новгород', url: '../../../sms.nov.mts.ru/default.htm', letter: 'Н', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1790, label: 'Новгородская область — Великий Новгород', url: '../../../www.dealers.nov.mts.ru/default.htm', letter: 'Н', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1731736, label: 'Новокузнецк', url: '../../../www.novokuznetsk.mts.ru/default.htm', letter: 'Н', iscountry: 0, parent: 1775, sitesection: 'ab', isLink: false },
{ id: 1731736, label: 'Новокузнецк', url: '../../../www.corp.novokuznetsk.mts.ru/default.htm', letter: 'Н', iscountry: 0, parent: 1775, sitesection: 'corp', isLink: false },
{ id: 1731736, label: 'Новокузнецк', url: '../../../www.company.novokuznetsk.mts.ru/default.htm', letter: 'Н', iscountry: 0, parent: 1775, sitesection: 'comp', isLink: false },
{ id: 1731736, label: 'Новокузнецк', url: '../../../www.dealers.novokuznetsk.mts.ru/default.htm', letter: 'Н', iscountry: 0, parent: 1775, sitesection: 'partn', isLink: false },
{ id: 1791, label: 'Новосибирская область', url: '../../../www.nsk.mts.ru/default.htm', letter: 'Н', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1791, label: 'Новосибирская область', url: '../../../www.corp.nsk.mts.ru/default.htm', letter: 'Н', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1791, label: 'Новосибирская область', url: '../../../www.company.nsk.mts.ru/default.htm', letter: 'Н', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1791, label: 'Новосибирская область', url: '../../../sms.nsk.mts.ru/default.htm', letter: 'Н', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1791, label: 'Новосибирская область', url: '../../../pdealer.mts.ru/default.htm', letter: 'Н', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1791, label: 'Новосибирская область', url: '../../../www.dealers.nsk.mts.ru/default.htm', letter: 'Н', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1792, label: 'Омская область', url: '../../../www.omsk.mts.ru/default.htm', letter: 'О', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1792, label: 'Омская область', url: '../../../www.corp.omsk.mts.ru/default.htm', letter: 'О', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1792, label: 'Омская область', url: '../../../www.company.omsk.mts.ru/default.htm', letter: 'О', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1792, label: 'Омская область', url: '../../../sms.omsk.mts.ru/default.htm', letter: 'О', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1792, label: 'Омская область', url: '../../../pdealer.mts.ru/default.htm', letter: 'О', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1792, label: 'Омская область', url: '../../../www.dealers.omsk.mts.ru/default.htm', letter: 'О', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1794, label: 'Оренбургская область', url: '../../../pdealer.mts.ru/default.htm', letter: 'О', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1794, label: 'Оренбургская область', url: '../../../www.orenburg.mts.ru/default.htm', letter: 'О', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1794, label: 'Оренбургская область', url: '../../../www.corp.orenburg.mts.ru/default.htm', letter: 'О', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1794, label: 'Оренбургская область', url: '../../../www.company.orenburg.mts.ru/default.htm', letter: 'О', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1794, label: 'Оренбургская область', url: '../../../sms.orenburg.mts.ru/default.htm', letter: 'О', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1794, label: 'Оренбургская область', url: '../../../www.dealers.orenburg.mts.ru/default.htm', letter: 'О', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1793, label: 'Орловская область', url: '../../../pdealer.mts.ru/default.htm', letter: 'О', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1793, label: 'Орловская область', url: '../../../www.orel.mts.ru/default.htm', letter: 'О', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1793, label: 'Орловская область', url: '../../../www.corp.orel.mts.ru/default.htm', letter: 'О', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1793, label: 'Орловская область', url: '../../../www.company.orel.mts.ru/default.htm', letter: 'О', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1793, label: 'Орловская область', url: '../../../sms.orel.mts.ru/default.htm', letter: 'О', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1793, label: 'Орловская область', url: '../../../www.dealers.orel.mts.ru/default.htm', letter: 'О', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 872778, label: 'Пензенская область', url: '../../../www.penza.mts.ru/default.htm', letter: 'П', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 872778, label: 'Пензенская область', url: '../../../www.corp.penza.mts.ru/default.htm', letter: 'П', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 872778, label: 'Пензенская область', url: '../../../www.company.penza.mts.ru/default.htm', letter: 'П', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 872778, label: 'Пензенская область', url: '../../../sms.penza.mts.ru/default.htm', letter: 'П', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 872778, label: 'Пензенская область', url: '../../../pdealer.mts.ru/default.htm', letter: 'П', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 872778, label: 'Пензенская область', url: '../../../www.dealers.penza.mts.ru/default.htm', letter: 'П', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1795, label: 'Пермский край', url: '../../../pdealer.mts.ru/default.htm', letter: 'П', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1795, label: 'Пермский край', url: '../../../www.perm.mts.ru/default.htm', letter: 'П', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1795, label: 'Пермский край', url: '../../../www.corp.perm.mts.ru/default.htm', letter: 'П', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1795, label: 'Пермский край', url: '../../../www.company.perm.mts.ru/default.htm', letter: 'П', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1795, label: 'Пермский край', url: '../../../sms.perm.mts.ru/default.htm', letter: 'П', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1795, label: 'Пермский край', url: '../../../www.dealers.perm.mts.ru/default.htm', letter: 'П', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1796, label: 'Приморский край — Владивосток', url: '../../../www.primorye.mts.ru/default.htm', letter: 'П', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1796, label: 'Приморский край — Владивосток', url: '../../../www.corp.primorye.mts.ru/default.htm', letter: 'П', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1796, label: 'Приморский край — Владивосток', url: '../../../www.company.primorye.mts.ru/default.htm', letter: 'П', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1796, label: 'Приморский край — Владивосток', url: '../../../sms.primorye.mts.ru/default.htm', letter: 'П', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1796, label: 'Приморский край — Владивосток', url: '../../../pdealer.mts.ru/default.htm', letter: 'П', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1796, label: 'Приморский край — Владивосток', url: '../../../www.dealers.primorye.mts.ru/default.htm', letter: 'П', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1797, label: 'Псковская область', url: '../../../pdealer.mts.ru/default.htm', letter: 'П', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1797, label: 'Псковская область', url: '../../../www.pskov.mts.ru/default.htm', letter: 'П', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1797, label: 'Псковская область', url: '../../../www.corp.pskov.mts.ru/default.htm', letter: 'П', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1797, label: 'Псковская область', url: '../../../www.company.pskov.mts.ru/default.htm', letter: 'П', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1797, label: 'Псковская область', url: '../../../sms.pskov.mts.ru/default.htm', letter: 'П', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1797, label: 'Псковская область', url: '../../../www.dealers.pskov.mts.ru/default.htm', letter: 'П', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1798, label: 'Ростовская область — Ростов-на-Дону', url: '../../../pdealer.mts.ru/', letter: 'Р', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1798, label: 'Ростовская область — Ростов-на-Дону', url: '../../../www.rnd.mts.ru/default.htm', letter: 'Р', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1798, label: 'Ростовская область — Ростов-на-Дону', url: '../../../www.vip.rnd.mts.ru/default.htm', letter: 'Р', iscountry: 0, parent: 0, sitesection: 'vip', isLink: false },
{ id: 1798, label: 'Ростовская область — Ростов-на-Дону', url: '../../../www.corp.rnd.mts.ru/default.htm', letter: 'Р', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1798, label: 'Ростовская область — Ростов-на-Дону', url: '../../../www.company.rnd.mts.ru/default.htm', letter: 'Р', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1798, label: 'Ростовская область — Ростов-на-Дону', url: '../../../sms.rnd.mts.ru/default.htm', letter: 'Р', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1798, label: 'Ростовская область — Ростов-на-Дону', url: '../../../pdealer.mts.ru/default.htm', letter: 'Р', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1798, label: 'Ростовская область — Ростов-на-Дону', url: '../../../www.dealers.rnd.mts.ru/default.htm', letter: 'Р', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1799, label: 'Рязанская область', url: '../../../pdealer.mts.ru/default.htm', letter: 'Р', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1799, label: 'Рязанская область', url: '../../../www.ryazan.mts.ru/default.htm', letter: 'Р', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1799, label: 'Рязанская область', url: '../../../www.corp.ryazan.mts.ru/default.htm', letter: 'Р', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1799, label: 'Рязанская область', url: '../../../www.company.ryazan.mts.ru/default.htm', letter: 'Р', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1799, label: 'Рязанская область', url: '../../../sms.ryazan.mts.ru/default.htm', letter: 'Р', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1799, label: 'Рязанская область', url: '../../../www.dealers.ryazan.mts.ru/default.htm', letter: 'Р', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1800, label: 'Самарская область', url: '../../../pdealer.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1800, label: 'Самарская область', url: '../../../www.samara.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1800, label: 'Самарская область', url: '../../../www.corp.samara.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1800, label: 'Самарская область', url: '../../../www.company.samara.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1800, label: 'Самарская область', url: '../../../sms.samara.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1800, label: 'Самарская область', url: '../../../www.dealers.samara.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1801, label: 'Санкт-Петербург, Ленинградская область', url: '../../../pdealer.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1801, label: 'Санкт-Петербург, Ленинградская область', url: '../../../www.spb.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1801, label: 'Санкт-Петербург, Ленинградская область', url: '../../../www.corp.spb.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1801, label: 'Санкт-Петербург, Ленинградская область', url: '../../../www.company.spb.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1801, label: 'Санкт-Петербург, Ленинградская область', url: '../../../sms.spb.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1801, label: 'Санкт-Петербург, Ленинградская область', url: '../../../www.dealers.spb.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1802, label: 'Саратовская область', url: '../../../pdealer.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1802, label: 'Саратовская область', url: '../../../www.saratov.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1802, label: 'Саратовская область', url: '../../../www.corp.saratov.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1802, label: 'Саратовская область', url: '../../../www.company.saratov.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1802, label: 'Саратовская область', url: '../../../sms.saratov.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1802, label: 'Саратовская область', url: '../../../www.dealers.saratov.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1803, label: 'Саха (Якутия) (Республика Саха (Якутия)) — Якутск', url: '../../../www.sakha.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1803, label: 'Саха (Якутия) (Республика Саха (Якутия)) — Якутск', url: '../../../www.corp.sakha.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1803, label: 'Саха (Якутия) (Республика Саха (Якутия)) — Якутск', url: '../../../www.company.sakha.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1803, label: 'Саха (Якутия) (Республика Саха (Якутия)) — Якутск', url: '../../../sms.sakha.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1803, label: 'Саха (Якутия) (Республика Саха (Якутия)) — Якутск', url: '../../../pdealer.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1803, label: 'Саха (Якутия) (Республика Саха (Якутия)) — Якутск', url: '../../../www.dealers.sakha.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1804, label: 'Сахалинская область — Южно-Сахалинск', url: '../../../www.sakh.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1804, label: 'Сахалинская область — Южно-Сахалинск', url: '../../../www.corp.sakh.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1804, label: 'Сахалинская область — Южно-Сахалинск', url: '../../../www.company.sakh.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1804, label: 'Сахалинская область — Южно-Сахалинск', url: '../../../sms.sakh.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1804, label: 'Сахалинская область — Южно-Сахалинск', url: '../../../pdealer.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1804, label: 'Сахалинская область — Южно-Сахалинск', url: '../../../www.dealers.sakh.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1805, label: 'Свердловская область — Екатеринбург', url: '../../../pdealer.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1805, label: 'Свердловская область — Екатеринбург', url: '../../../www.e-burg.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1805, label: 'Свердловская область — Екатеринбург', url: '../../../www.corp.e-burg.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1805, label: 'Свердловская область — Екатеринбург', url: '../../../www.company.e-burg.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1805, label: 'Свердловская область — Екатеринбург', url: '../../../sms.e-burg.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1805, label: 'Свердловская область — Екатеринбург', url: '../../../www.dealers.e-burg.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1760597, label: 'Сергиев Посад', url: '../../../www.s-posad.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 1826, sitesection: 'ab', isLink: false },
{ id: 1760597, label: 'Сергиев Посад', url: '../../../www.corp.s-posad.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 1826, sitesection: 'corp', isLink: false },
{ id: 1760597, label: 'Сергиев Посад', url: '../../../www.company.s-posad.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 1826, sitesection: 'comp', isLink: false },
{ id: 1760597, label: 'Сергиев Посад', url: '../../../www.dealers.s-posad.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 1826, sitesection: 'partn', isLink: false },
{ id: 1807, label: 'Смоленская область', url: '../../../pdealer.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1807, label: 'Смоленская область', url: '../../../www.smolensk.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1807, label: 'Смоленская область', url: '../../../www.corp.smolensk.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1807, label: 'Смоленская область', url: '../../../www.company.smolensk.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1807, label: 'Смоленская область', url: '../../../sms.smolensk.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1807, label: 'Смоленская область', url: '../../../www.dealers.smolensk.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1971608, label: 'Сосновый Бор', url: '../../../www.sbor.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 1801, sitesection: 'ab', isLink: false },
{ id: 1971608, label: 'Сосновый Бор', url: '../../../www.corp.sbor.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 1801, sitesection: 'corp', isLink: false },
{ id: 1971608, label: 'Сосновый Бор', url: '../../../www.company.sbor.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 1801, sitesection: 'comp', isLink: false },
{ id: 1971608, label: 'Сосновый Бор', url: '../../../www.dealers.sbor.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 1801, sitesection: 'partn', isLink: false },
{ id: 1806, label: 'Ставропольский край', url: '../../../pdealer.mts.ru/', letter: 'С', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1806, label: 'Ставропольский край', url: '../../../www.stavropol.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1806, label: 'Ставропольский край', url: '../../../www.vip.stavropol.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'vip', isLink: false },
{ id: 1806, label: 'Ставропольский край', url: '../../../www.corp.stavropol.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1806, label: 'Ставропольский край', url: '../../../www.company.stavropol.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1806, label: 'Ставропольский край', url: '../../../sms.stavropol.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1806, label: 'Ставропольский край', url: '../../../pdealer.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1806, label: 'Ставропольский край', url: '../../../www.dealers.stavropol.mts.ru/default.htm', letter: 'С', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1810, label: 'Тамбовская область', url: '../../../pdealer.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1810, label: 'Тамбовская область', url: '../../../www.tambov.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1810, label: 'Тамбовская область', url: '../../../www.corp.tambov.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1810, label: 'Тамбовская область', url: '../../../www.company.tambov.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1810, label: 'Тамбовская область', url: '../../../sms.tambov.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1810, label: 'Тамбовская область', url: '../../../www.dealers.tambov.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1808, label: 'Татарстан (Республика Татарстан) — Казань', url: '../../../pdealer.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1808, label: 'Татарстан (Республика Татарстан) — Казань', url: '../../../www.tatarstan.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1808, label: 'Татарстан (Республика Татарстан) — Казань', url: '../../../www.corp.tatarstan.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1808, label: 'Татарстан (Республика Татарстан) — Казань', url: '../../../www.company.tatarstan.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1808, label: 'Татарстан (Республика Татарстан) — Казань', url: '../../../sms.tatarstan.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1808, label: 'Татарстан (Республика Татарстан) — Казань', url: '../../../sms.tatarstan.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1808, label: 'Татарстан (Республика Татарстан) — Казань', url: '../../../www.dealers.tatarstan.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1811, label: 'Тверская область', url: '../../../pdealer.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1811, label: 'Тверская область', url: '../../../www.tver.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1811, label: 'Тверская область', url: '../../../www.corp.tver.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1811, label: 'Тверская область', url: '../../../www.company.tver.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1811, label: 'Тверская область', url: '../../../sms.tver.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1811, label: 'Тверская область', url: '../../../www.dealers.tver.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1903669, label: 'Тобольск', url: '../../../www.tobolsk.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 1815, sitesection: 'ab', isLink: false },
{ id: 1903669, label: 'Тобольск', url: '../../../www.corp.tobolsk.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 1815, sitesection: 'corp', isLink: false },
{ id: 1903669, label: 'Тобольск', url: '../../../www.company.tobolsk.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 1815, sitesection: 'comp', isLink: false },
{ id: 1903669, label: 'Тобольск', url: '../../../www.dealers.tobolsk.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 1815, sitesection: 'partn', isLink: false },
{ id: 1812, label: 'Томская область', url: '../../../www.tomsk.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1812, label: 'Томская область', url: '../../../www.corp.tomsk.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1812, label: 'Томская область', url: '../../../www.company.tomsk.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1812, label: 'Томская область', url: '../../../sms.tomsk.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1812, label: 'Томская область', url: '../../../pdealer.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1812, label: 'Томская область', url: '../../../www.dealers.tomsk.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1813, label: 'Тульская область', url: '../../../pdealer.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1813, label: 'Тульская область', url: '../../../www.tula.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1813, label: 'Тульская область', url: '../../../www.corp.tula.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1813, label: 'Тульская область', url: '../../../www.company.tula.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1813, label: 'Тульская область', url: '../../../sms.tula.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1813, label: 'Тульская область', url: '../../../www.dealers.tula.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1814, label: 'Тыва (Республика Тыва) — Кызыл', url: '../../../www.tyva.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1814, label: 'Тыва (Республика Тыва) — Кызыл', url: '../../../www.corp.tyva.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1814, label: 'Тыва (Республика Тыва) — Кызыл', url: '../../../www.company.tyva.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1814, label: 'Тыва (Республика Тыва) — Кызыл', url: '../../../sms.tyva.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1814, label: 'Тыва (Республика Тыва) — Кызыл', url: '../../../pdealer.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1814, label: 'Тыва (Республика Тыва) — Кызыл', url: '../../../www.dealers.tyva.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1815, label: 'Тюменская область', url: '../../../pdealer.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1815, label: 'Тюменская область', url: '../../../www.tyumen.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1815, label: 'Тюменская область', url: '../../../www.corp.tyumen.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1815, label: 'Тюменская область', url: '../../../www.company.tyumen.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1815, label: 'Тюменская область', url: '../../../sms.tyumen.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1815, label: 'Тюменская область', url: '../../../www.dealers.tyumen.mts.ru/default.htm', letter: 'Т', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1816, label: 'Удмуртия (Удмуртская Республика) — Ижевск', url: '../../../pdealer.mts.ru/default.htm', letter: 'У', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1816, label: 'Удмуртия (Удмуртская Республика) — Ижевск', url: '../../../www.udm.mts.ru/default.htm', letter: 'У', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1816, label: 'Удмуртия (Удмуртская Республика) — Ижевск', url: '../../../www.corp.udm.mts.ru/default.htm', letter: 'У', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1816, label: 'Удмуртия (Удмуртская Республика) — Ижевск', url: '../../../www.company.udm.mts.ru/default.htm', letter: 'У', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1816, label: 'Удмуртия (Удмуртская Республика) — Ижевск', url: '../../../sms.udm.mts.ru/default.htm', letter: 'У', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1816, label: 'Удмуртия (Удмуртская Республика) — Ижевск', url: '../../../sms.udm.mts.ru/default.htm', letter: 'У', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1816, label: 'Удмуртия (Удмуртская Республика) — Ижевск', url: '../../../www.dealers.udm.mts.ru/default.htm', letter: 'У', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1817, label: 'Ульяновская область', url: '../../../pdealer.mts.ru/default.htm', letter: 'У', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1817, label: 'Ульяновская область', url: '../../../www.uln.mts.ru/default.htm', letter: 'У', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1817, label: 'Ульяновская область', url: '../../../www.corp.uln.mts.ru/default.htm', letter: 'У', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1817, label: 'Ульяновская область', url: '../../../www.company.uln.mts.ru/default.htm', letter: 'У', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1817, label: 'Ульяновская область', url: '../../../sms.uln.mts.ru/default.htm', letter: 'У', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1817, label: 'Ульяновская область', url: '../../../www.dealers.uln.mts.ru/default.htm', letter: 'У', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1818, label: 'Хабаровский край', url: '../../../www.khv.mts.ru/default.htm', letter: 'Х', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1818, label: 'Хабаровский край', url: '../../../www.corp.khv.mts.ru/default.htm', letter: 'Х', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1818, label: 'Хабаровский край', url: '../../../www.company.khv.mts.ru/default.htm', letter: 'Х', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1818, label: 'Хабаровский край', url: '../../../sms.khv.mts.ru/default.htm', letter: 'Х', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1818, label: 'Хабаровский край', url: '../../../pdealer.mts.ru/default.htm', letter: 'Х', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1818, label: 'Хабаровский край', url: '../../../www.dealers.khv.mts.ru/default.htm', letter: 'Х', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1820, label: 'Хакасия (Республика Хакасия) — Абакан', url: '../../../www.khakasia.mts.ru/default.htm', letter: 'Х', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1820, label: 'Хакасия (Республика Хакасия) — Абакан', url: '../../../www.corp.khakasia.mts.ru/default.htm', letter: 'Х', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1820, label: 'Хакасия (Республика Хакасия) — Абакан', url: '../../../www.company.khakasia.mts.ru/default.htm', letter: 'Х', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1820, label: 'Хакасия (Республика Хакасия) — Абакан', url: '../../../sms.khakasia.mts.ru/default.htm', letter: 'Х', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1820, label: 'Хакасия (Республика Хакасия) — Абакан', url: '../../../pdealer.mts.ru/default.htm', letter: 'Х', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1820, label: 'Хакасия (Республика Хакасия) — Абакан', url: '../../../www.dealers.khakasia.mts.ru/default.htm', letter: 'Х', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1819, label: 'Ханты-Мансийский АО — Югра  —  Ханты-Мансийск', url: '../../../pdealer.mts.ru/default.htm', letter: 'Х', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1819, label: 'Ханты-Мансийский АО — Югра  —  Ханты-Мансийск', url: '../../../www.yugra.mts.ru/default.htm', letter: 'Х', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1819, label: 'Ханты-Мансийский АО — Югра  —  Ханты-Мансийск', url: '../../../www.corp.yugra.mts.ru/default.htm', letter: 'Х', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1819, label: 'Ханты-Мансийский АО — Югра  —  Ханты-Мансийск', url: '../../../www.company.yugra.mts.ru/default.htm', letter: 'Х', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1819, label: 'Ханты-Мансийский АО — Югра  —  Ханты-Мансийск', url: '../../../sms.yugra.mts.ru/default.htm', letter: 'Х', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1819, label: 'Ханты-Мансийский АО — Югра  —  Ханты-Мансийск', url: '../../../www.dealers.yugra.mts.ru/default.htm', letter: 'Х', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1821, label: 'Челябинская область', url: '../../../pdealer.mts.ru/default.htm', letter: 'Ч', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1821, label: 'Челябинская область', url: '../../../www.chel.mts.ru/default.htm', letter: 'Ч', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1821, label: 'Челябинская область', url: '../../../www.corp.chel.mts.ru/default.htm', letter: 'Ч', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1821, label: 'Челябинская область', url: '../../../www.company.chel.mts.ru/default.htm', letter: 'Ч', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1821, label: 'Челябинская область', url: '../../../sms.chel.mts.ru/default.htm', letter: 'Ч', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1821, label: 'Челябинская область', url: '../../../www.dealers.chel.mts.ru/default.htm', letter: 'Ч', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1941897, label: 'Чехов', url: '../../../www.chehov.mts.ru/default.htm', letter: 'Ч', iscountry: 0, parent: 1826, sitesection: 'ab', isLink: false },
{ id: 1941897, label: 'Чехов', url: '../../../www.corp.chehov.mts.ru/default.htm', letter: 'Ч', iscountry: 0, parent: 1826, sitesection: 'corp', isLink: false },
{ id: 1941897, label: 'Чехов', url: '../../../www.company.chehov.mts.ru/default.htm', letter: 'Ч', iscountry: 0, parent: 1826, sitesection: 'comp', isLink: false },
{ id: 1941897, label: 'Чехов', url: '../../../www.dealers.chehov.mts.ru/default.htm', letter: 'Ч', iscountry: 0, parent: 1826, sitesection: 'partn', isLink: false },
{ id: 782519, label: 'Чеченская Республика', url: '../../../pdealer.mts.ru/', letter: 'Ч', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 782519, label: 'Чеченская Республика', url: '../../../www.chechnya.mts.ru/default.htm', letter: 'Ч', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 782519, label: 'Чеченская Республика', url: '../../../www.corp.chechnya.mts.ru/default.htm', letter: 'Ч', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 782519, label: 'Чеченская Республика', url: '../../../www.company.chechnya.mts.ru/default.htm', letter: 'Ч', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 782519, label: 'Чеченская Республика', url: '../../../sms.chechnya.mts.ru/default.htm', letter: 'Ч', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 782519, label: 'Чеченская Республика', url: '../../../www.dealers.chechnya.mts.ru/default.htm', letter: 'Ч', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1823, label: 'Чувашская республика — Чебоксары', url: '../../../pdealer.mts.ru/default.htm', letter: 'Ч', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1823, label: 'Чувашская республика — Чебоксары', url: '../../../www.chuvashia.mts.ru/default.htm', letter: 'Ч', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1823, label: 'Чувашская республика — Чебоксары', url: '../../../www.corp.chuvashia.mts.ru/default.htm', letter: 'Ч', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1823, label: 'Чувашская республика — Чебоксары', url: '../../../www.company.chuvashia.mts.ru/default.htm', letter: 'Ч', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1823, label: 'Чувашская республика — Чебоксары', url: '../../../sms.chuvashia.mts.ru/default.htm', letter: 'Ч', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1823, label: 'Чувашская республика — Чебоксары', url: '../../../sms.chuvashia.mts.ru/default.htm', letter: 'Ч', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1823, label: 'Чувашская республика — Чебоксары', url: '../../../www.dealers.chuvashia.mts.ru/default.htm', letter: 'Ч', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1829, label: 'Чукотский АО - Анадырь', url: '../../../www.chukotka.mts.ru/default.htm', letter: 'Ч', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1829, label: 'Чукотский АО - Анадырь', url: '../../../www.corp.chukotka.mts.ru/default.htm', letter: 'Ч', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1829, label: 'Чукотский АО - Анадырь', url: '../../../www.company.chukotka.mts.ru/default.htm', letter: 'Ч', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1829, label: 'Чукотский АО - Анадырь', url: '../../../sms.chukotka.mts.ru/default.htm', letter: 'Ч', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1829, label: 'Чукотский АО - Анадырь', url: '../../../pdealer.mts.ru/default.htm', letter: 'Ч', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1829, label: 'Чукотский АО - Анадырь', url: '../../../www.dealers.chukotka.mts.ru/default.htm', letter: 'Ч', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1824, label: 'Ямало-Ненецкий АО — Салехард', url: '../../../pdealer.mts.ru/default.htm', letter: 'Я', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1824, label: 'Ямало-Ненецкий АО — Салехард', url: '../../../www.yamal.mts.ru/default.htm', letter: 'Я', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1824, label: 'Ямало-Ненецкий АО — Салехард', url: '../../../www.corp.yamal.mts.ru/default.htm', letter: 'Я', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1824, label: 'Ямало-Ненецкий АО — Салехард', url: '../../../www.company.yamal.mts.ru/default.htm', letter: 'Я', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1824, label: 'Ямало-Ненецкий АО — Салехард', url: '../../../sms.yamal.mts.ru/default.htm', letter: 'Я', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1824, label: 'Ямало-Ненецкий АО — Салехард', url: '../../../www.dealers.yamal.mts.ru/default.htm', letter: 'Я', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: 1825, label: 'Ярославская область', url: '../../../pdealer.mts.ru/default.htm', letter: 'Я', iscountry: 0, parent: 0, sitesection: 'deal', isLink: false },
{ id: 1825, label: 'Ярославская область', url: '../../../www.yaroslavl.mts.ru/default.htm', letter: 'Я', iscountry: 0, parent: 0, sitesection: 'ab', isLink: false },
{ id: 1825, label: 'Ярославская область', url: '../../../www.corp.yaroslavl.mts.ru/default.htm', letter: 'Я', iscountry: 0, parent: 0, sitesection: 'corp', isLink: false },
{ id: 1825, label: 'Ярославская область', url: '../../../www.company.yaroslavl.mts.ru/default.htm', letter: 'Я', iscountry: 0, parent: 0, sitesection: 'comp', isLink: false },
{ id: 1825, label: 'Ярославская область', url: '../../../sms.yaroslavl.mts.ru/default.htm', letter: 'Я', iscountry: 0, parent: 0, sitesection: 'extra', isLink: false },
{ id: 1825, label: 'Ярославская область', url: '../../../www.dealers.yaroslavl.mts.ru/default.htm', letter: 'Я', iscountry: 0, parent: 0, sitesection: 'partn', isLink: false },
{ id: -1, label: 'Коттеджные поселки', url: '../../../www.mts.ru/mts_stream/help/region_podmoskov/default.htm', letter: 'М', iscountry: 0, parent: 1826, sitesection: 'ab', isLink: true },
];
function AddRenamedRegion(alias, name, newName){
                	if (!renamedRegions[alias])
                	{
                		renamedRegions[alias] = {};
                	}
                	renamedRegions[alias][name] = newName;
                }
 var renamedRegions = {};
AddRenamedRegion('mts_stream', 'Москва и Подмосковье', '&nbsp;&nbsp;Москва&nbsp;&nbsp;');
